name: unet_L1_loss_1_conv
root_dir: "/home/baoluli/personal/1.dataset/opv2v_adverse_weather/fog_value_0.008/train"
validate_dir: "/home/baoluli/personal/1.dataset/opv2v_adverse_weather/fog_value_0.008/test_culver_city"

train_params:
  batch_size: &batch_size 4
  epoches: 100
  eval_freq: 1
  save_freq: 1

model:
  core_method: unet
  args:
    in_channels: 384
    out_channels: 384

loss:
  core_method: L1_loss
  args:

# loss:
#   core_method: point_pillar_loss
#   args:
#     cls_weight: 1.0
#     reg: 2.0


optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [10, 15]