name: point_pillar_intermediate_fusion_mldg_a #_align_agent_20_5_fusion_1_1 #point_pillar_intermediate_fusion_metric_1_setting_6
root_dir: "/home/baoluli/personal/1.dataset/V2X/train"
validate_dir: "/home/baoluli/personal/1.dataset/V2X/test"
save_dir: "/home/baoluli/personal/2.model_saved/4.Adverseweather/v2xset_DG"




yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 2
  epoches: 20
  eval_freq: 1
  save_freq: 1

DG_params:
  Is_DG: False
  DG_validate_num: 9
  DG_validate_name: ['opv2v-small-snow','opv2v-small-fog','opv2v-small-rain ','opv2v-large-snow','opv2v-large-fog','opv2v-large-rain','v2xset-snow','v2xset-fog','v2xset-rain']
  DG_validate_dir: ['/home/baoluli/personal/1.dataset/opv2v_adverse_weather/snow_severity_new_4/test_culver_city',
                    '/home/baoluli/personal/1.dataset/opv2v_adverse_weather/fog_value_0.008/test_culver_city',
                    '/home/baoluli/personal/1.dataset/opv2v_adverse_weather/rain_severity_10/test_culver_city',
                    '/home/baoluli/personal/1.dataset/opv2v_adverse_weather/snow_severity_new_5/test',
                    '/home/baoluli/personal/1.dataset/opv2v_adverse_weather/fog_value_0.008/test',
                    '/home/baoluli/personal/1.dataset/opv2v_adverse_weather/rain_severity_7/test',
                    '/home/baoluli/personal/1.dataset/V2X_adverse_weather/19/test',
                    '/home/baoluli/personal/1.dataset/V2X_adverse_weather/22/test',
                    '/home/baoluli/personal/1.dataset/V2X_adverse_weather/rain_severity_7/test']
  Augment_params:
    dynamic_range: True
    range_proportion_low: 0.5
    range_proportion_high: 0.5
    random_drop_out: True
    random_guss_noise: True
    random_jittering: True

  Agent_level_align: True
  agent_level_test_method: 0 #20
  #Agent_align_level: 0
  Agent_level_align_weight: 0.1

  Fusion_level_align: True
  fusion_level_test_method: 1
  Fusion_level_align_weight: 1

  Agent_level_metric: True
  Agent_level_metric_weight: 0.01
  Agent_level_metric_method: 1
  Agent_metric_level: 0
  Agent_level_metric_learner: true
  Agent_level_metric_learner_args:
      in_channel: 384
      out_channel: 128
      setting: 7

  Fusion_level_metric: True
  Fusion_level_metric_weight: 0.01
  fusion_level_metric_method: 1
  Fusion_level_metric_learner: true
  Fusion_level_metric_learner_args:
      in_channel: 384
      out_channel: 128
      setting: 7


fusion:
  core_method: 'IntermediateFusionDataset' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args: []

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 4]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  # lidar range for each individual cav.
  cav_lidar_range: &cav_lidar [-140.8, -40, -3, 140.8, 40, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 2
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

# model related
model:
  core_method: point_pillar_intermediate
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
      compression: 0

    cls_head_dim: 384
    anchor_num: *achor_num

loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [10, 15]